name: mzml_tools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - numpy
    - pyteomics
    - pymzml
    - psims
    - scipy
    - numpy
    - pandas
    - matplotlib 
    - pyopenms
